# Generated by Django 3.2.4 on 2021-08-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0002_disease_feedback_healthtips_news_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthTips',
            new_name='HealthTip',
        ),
    ]
