# Generated by Django 3.2.4 on 2021-09-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0003_rename_healthtips_healthtip'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
