# Generated by Django 3.2.4 on 2021-10-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0005_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='dob',
        ),
    ]
