# Generated by Django 3.2.4 on 2021-10-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0006_remove_doctor_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
