# Generated by Django 3.2.4 on 2021-10-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0007_delete_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=300, null=True)),
                ('symptoms', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('advice', models.TextField(null=True)),
                ('img1', models.FileField(null=True, upload_to='')),
                ('img2', models.FileField(null=True, upload_to='')),
                ('img3', models.FileField(null=True, upload_to='')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartapp.doctor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartapp.userprofile')),
            ],
        ),
    ]
