# Generated by Django 3.2.4 on 2021-10-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0008_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='identification',
            name='fname',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
