# Generated by Django 3.2.4 on 2021-10-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0009_auto_20211024_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='img1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='identification',
            name='img2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='identification',
            name='img3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
