# Generated by Django 3.2.4 on 2021-10-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0011_auto_20211024_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='additionalImages/'),
        ),
    ]
