# Generated by Django 3.2.4 on 2021-10-24 12:50

from django.db import migrations, models
import smartapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0012_alter_identification_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.FileField(null=True, upload_to=smartapp.models.doc_directory_path),
        ),
        migrations.AlterField(
            model_name='identification',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='additionalImages/'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='additionalImages/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(null=True, upload_to='newsImages/%y%m%d/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(null=True, upload_to=smartapp.models.user_directory_path),
        ),
    ]
