# Generated by Django 3.2.4 on 2021-10-24 13:15

from django.db import migrations, models
import smartapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0013_auto_20211024_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=smartapp.models.additional_directory_path),
        ),
        migrations.AlterField(
            model_name='identification',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=smartapp.models.additional_directory_path),
        ),
        migrations.AlterField(
            model_name='identification',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=smartapp.models.additional_directory_path),
        ),
    ]
