# Generated by Django 3.2.4 on 2021-10-25 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0015_alter_identification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartapp.userprofile'),
        ),
    ]
