# Generated by Django 3.2.4 on 2021-10-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0019_alter_consult_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consult',
            old_name='doctor',
            new_name='doc',
        ),
    ]
