# Generated by Django 3.2.4 on 2021-10-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0020_rename_doctor_consult_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
