# Generated by Django 3.2.4 on 2021-10-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0023_healthtip_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, null=True)),
                ('content', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to='newsImages/%y%m%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='HealthTip',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
