# Generated by Django 3.2.4 on 2021-10-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0024_auto_20211027_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthTipCategory',
            new_name='ArticleCategory',
        ),
    ]
