# Generated by Django 3.2.4 on 2022-08-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0027_alter_consult_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nic',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
