# Generated by Django 3.2.4 on 2022-08-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0029_auto_20220818_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slmc',
            field=models.IntegerField(null=True),
        ),
    ]
