# Generated by Django 3.2.4 on 2022-08-31 10:20

from django.db import migrations, models
import smartapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0030_doctor_slmc'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='prescribe_img',
            field=models.ImageField(blank=True, null=True, upload_to=smartapp.models.additional_directory_path),
        ),
    ]
